name: Actions
on:
    push

jobs:
    build:
        name: Run build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies
              run: yarn install

            - name: Compile contracts
              run: yarn compile

    lint:
        name: Run lints
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies
              run: yarn install

            - name: Run Prettier
              run: yarn run lint

    test:
        name: Run tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies
              run: yarn install

            - name: Compile contracts
              run: yarn compile
            
            - name: Test contracts
              run: yarn test